---
- name: Remove default nginx site to avoid conflicts
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: true
    state: present

- name: Create /etc/nginx/conf.d directory
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory

- name: Deploy upstream config for myapp
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/myapp.conf
  notify: Restart nginx
