---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecret.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.image.pullSecret.registry }}": {
          "username": "{{ .Values.image.pullSecret.username }}",
          "email": "{{ .Values.image.pullSecret.email }}",
          "password": "{{ .Values.image.pullSecret.password }}"
        }
      }
    }
