---
apiVersion: v1
kind: Secret
metadata:
  name: intern-image-pull-secret
  namespace: intern
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "msvetnikov",
          "email": "msvet813@gmail.com",
          "password": ""
        }
      }
    }
